version: 2.1

#######################################################################################
# GitHub:   https://github.com/rvshare/lighthouse-stats-circleci/blob/master/src/@orb.yml #
# CircleCI: https://circleci.com/orbs/registry/orb/rvshare/lighthouse-stats      #
#######################################################################################

description: |
  Record Google Lighthouse reports in a repository automatically
  Source Code: https://github.com/rvshare/lighthouse-stats-circleci/blob/master/src/@orb.yml

executors:
  node:
    docker:
      - image: circleci/node:10-browsers
  ruby:
    docker:
      - image: circleci/ruby:2.6.1

jobs:
  measure:
    parameters:
      url:
        type: string
        description: URL to be tested
      folder_prefix:
        type: string
        description: Prefix of the file name
      executor:
        type: executor
        default: node
    executor: << parameters.executor >>
    steps:
      - run: node --version
      - run: yarn versions

      - restore_cache:
          keys:
            - v0-rvshare-lighthouse-stats-yarn-cache-{{ arch }}-
      - run: yarn global add lighthouse
      - save_cache:
          key: v0-rvshare-lighthouse-stats-yarn-cache-{{ arch }}-{{ epoch }}
          paths:
            - ~/.yarn/cache

      - run: $(yarn global bin)/lighthouse --version

      - run: mkdir -p stats/<< parameters.folder_prefix >>
      - run:
          command: $(yarn global bin)/lighthouse "<< parameters.url >>" --output=json --output=html --verbose || true
          working_directory: stats/<< parameters.folder_prefix >>

      - persist_to_workspace:
          root: ~/project
          paths:
            - stats

  commit:
    parameters:
      git_user_email:
        type: string
        description: Git committer email
      git_user_name:
        type: string
        description: Git committer name
      git_ssh_fingerprint:
        type: string
        description: Git committer SSH fingerprint (with write access to the git repository)
      readme_generator_script:
        type: string
        description: Git committer SSH fingerprint
        default: https://raw.githubusercontent.com/rvshare/lighthouse-stats-circleci/master/src/generate_readme.rb
      executor:
        type: executor
        default: ruby
    executor: << parameters.executor >>
    steps:
      - run: ruby --version

      - run: git config --global user.email << parameters.git_user_email >>
      - run: git config --global user.name << parameters.git_user_name >>

      - checkout
      - attach_workspace:
          at: ~/project

      - run: git add stats/*.{html,json}
      - run: git status

      - run: curl << parameters.readme_generator_script >> | ruby
      - run: git add LIGHTHOUSE_REPORTS.md

      - run: git status
      - run: |
          git commit -m "[ci skip] Added Lighthouse reports - CircleCI #$CIRCLE_BUILD_NUM" -m $CIRCLE_BUILD_URL

      - add_ssh_keys:
          fingerprints:
            - << parameters.git_ssh_fingerprint >>
      - run: git push origin master
