require 'erb'
require 'json'


sites = Dir.chdir('stats') do
  Dir.glob('*').select { |f| File.directory? f }
end

latest_jsons = sites.map do |site|
  Dir.glob(File.join('stats', site, '*.json')).max_by(&File.method(:ctime))
end.reject(&:nil?)

items = latest_jsons.map do |json|
  data = JSON.parse(File.read(json), symbolize_names: true)

  {
    json: json,
    requested_url: data.dig(:requestedUrl),
    created_at: data.dig(:fetchTime),
    performance: data.dig(:categories, :performance, :score) * 100,
    accessibility: data.dig(:categories, :accessibility, :score) * 100,
    best_practices: data.dig(:categories, :"best-practices", :score) * 100,
    seo: data.dig(:categories, :seo, :score) * 100,
    pwa: data.dig(:categories, :pwa, :score) * 100
  }
end

# Create template.
template = %q{
  # Lighthouse Site Performance Report

  **Updated at <%= Time.now %> by [CircleCI #<%= ENV['CIRCLE_BUILD_NUM'] %>](<%= ENV['CIRCLE_BUILD_URL'] %>)**

  **This report was automatically generated by [Lighthouse stats](https://github.com/jamesmosier/lighthouse-stats-circleci)*

  | URL | Performance | Accessibility | Best Practices | SEO | PWA | Updated At |
  | --- | --- | --- | --- | --- | --- | --- |
  % items.each do |item|
    | [<%= item.dig(:requested_url) %>](./<%= item.dig(:json) %>) | <%= item.dig(:performance).round %>% | <%= item.dig(:accessibility).round %>% | <%= item.dig(:best_practices).round %>% | <%= item.dig(:seo).round %>% | <%= item.dig(:pwa).round %>% | <%= item.dig(:created_at) %> |
  % end
}.gsub(/^ +/, '')

erb = ERB.new(template, 0, "%<>")

File.open('LIGHTHOUSE_REPORTS.md', 'w') do |f|
  f.write erb.result
end
